config/routes.rb
Rails.application.routes.draw do
  root 'lists#new'

  resources :lists, only: [:new, :create, :show, :index] do
    get 'rank', on: :member
  end

  resources :items, only: [] do
    post 'upvote', on: :member
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
  validates_presence_of :name
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items

  validates_presence_of :name

  def items_to_rank
    return nil if items.empty?
    items.shuffle.combination(2).to_a.each do |pair|
      return pair if pair[0].votes == pair[1].votes
    end
    nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def upvote
    item = Item.find(params[:id])
    item.increment!(:votes)

    redirect_to rank_list_path(item.list)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      create_list_items
      redirect_to rank_list_path(@list)
    else
      render :new
    end
  end

  def show
    @list = List.find(params[:id])
    @items = @list.items.order(votes: :desc)
  end

  def index
    @lists = List.all
  end

  def rank
    list = List.find(params[:id])
    @items = list.items_to_rank

    if @items.nil?
      redirect_to list, notice: 'Ranking complete!'
    end
  end

  private

  def list_params
    params.required(:list).permit(:name)
  end

  def create_list_items
    contents = params[:list][:text_file].read
    # contents needs to be a string where items are delineated by newlines (\n)
    contents.split("\n").each do |item_name|
      @list.items.create!(name: item_name)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rank All the Things!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "flash #{key}") %>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/lists/index.html.haml
= render 'shared/menu'

%h1.container All the Lists!

%ul.container.all-lists
  - @lists.each do |list|
    %li= link_to "#{list.name}", list
    %br

app/views/lists/new.html.haml
- if @list.errors.any?
  - @list.errors.full_messages.each do |msg|
    .flash.alert= msg

%h1.center Rank All the Things!*

= form_for @list do |f|
  = f.label :name, 'List Name:'
  = f.text_field :name
  = f.file_field :text_file
  %br
  %br
  = f.submit 'Let the ranking begin!'

#all-the-things.center= image_tag 'all_the_things.png'
%br

.center
  = link_to 'See All the Lists', '/lists'
%br
%br

.fine-print *"All the Things" must be contained in a plain .txt file (no special characters). A single newline should separate each thing from the next.

app/views/lists/rank.html.haml
= render 'shared/menu'

.voting
  - @items.each do |item|
    = link_to "#{ item.name }", upvote_item_path(item), method: :post
    - unless item == @items.last
      %br
      %br
      vs.
      %br
      %br

%br
%br

.center
  = link_to 'Skip', rank_list_path

app/views/lists/show.html.haml
= render 'shared/menu'

%h1.container= @list.name

- if @list.items_to_rank
  .container= link_to 'Rank more things!', rank_list_path(@list)

%ol.container
  - @items.each do |item|
    - item.votes == 1 ? label = 'vote' : label = 'votes'
    %li= "#{item.name} (#{item.votes} #{label})"

app/views/shared/_menu.html.haml
%ul.nav-bar
  %li.nav-link
    = link_to 'Home', '/'
  %li.nav-link
    = link_to 'Lists', '/lists'